### PR TITLE
Hero Profile app (Narek Avagian)

### PR DESCRIPTION
**Pull request by nrkvg**

### CODE REVIEW

**Comment by mascarpony** [comment]
I love this questionary, it looks amazing! Have you worked as a layout designer before?)

I have a few comments for you:
1. If you want to handle contacts as array, the better option is to make array of them. ObjectKeys is overhead
2. `target.parentNode.parentNode.parentNode.classList.toggle('hide-answer');` looks not in Angular way and depends too much from mark-up levels. Can you find another solution? For example, you can create a component for the questionary option and store the toggle state in the component properties
3. What purposes shared and core folders have? (I don't think that you are wrong, I just want to check the logic)

In common, it's 3/3 🥇

**Comment by nrkvg** [comment]
I haven't worked as a designer, I'm just little crazy about beautiful interfaces :) You can check my [portfolio](https://drednes.github.io) if you are interested in my other pet projects

About 1 and 2 points: I was just too lazy to do it better, but I can refactor that things

About folder structure: I don't know :)) I had just searched for “common angular folder structure” and used found structure from first link

I'm really 'react lover' kind of person, so angular is new for me, despite the fact that I work with it on lab project.

**Comment by mascarpony** [comment]
Checked last changes, now it's fine 👍 

> About folder structure: I don't know :)) I had just searched for “common angular folder structure” and used found structure from first link

)))))) Good that you thought about it

The portfolio is really pretty) Especially Github cat 😍

**Comment by nrkvg** [comment]
Thank you, it’s nice to hear it from you :)

**Pull request closed without merging**
